#   orders(first: 15, query: "updated_at:>2022-12-18")
# orders(first: 1, query: "name:#1085")
{
  orders(first:20){
    nodes{
      name
      updatedAt
      lineItems(first: 10){
        nodes{
          name
          quantity
          originalTotalSet{shopMoney{amount}}
          originalUnitPriceSet{shopMoney{amount}}
        }
      }
      originalTotalPriceSet{shopMoney{amount}}
      subtotalLineItemsQuantity
      customer{
        displayName
      }
      paymentGatewayNames
      transactions(first:10){
        id
      accountNumber
      formattedGateway
      gateway
      createdAt
      kind
      paymentIcon{altText}
      processedAt
      status
      totalUnsettledSet{shopMoney{amount}}
      amountSet{shopMoney{amount}}
      paymentIcon {
        altText
      }
      }
    }
  }
}

