
# orders(first: 15, query: "updated_at:>2022-12-18") #the date string needs to be updatable
# orders(first: 1, query: "name:#1085") # two orders and tip, no customer name
# orders(first: 1, query: "name:#1005") # one order and customer name


query {
  orders(first: 500, query: "updated_at:>2022-12-18") {
    nodes {
      name
      updatedAt
      lineItems(first: 10) {
        ...ProductSold
      }
      originalTotalPriceSet {
        ...PriceAmount
      }
      subtotalLineItemsQuantity
      customer {
        displayName
      }
      transactions(first: 10) {
        ...PaymentTransactionDetails
      }
    }
  }
}

fragment ProductSold on LineItemConnection {
  nodes {
    name
    quantity
    originalTotalSet {
      ...PriceAmount
    }
    originalUnitPriceSet {
      ...PriceAmount
    }
  }
}

fragment PriceAmount on MoneyBag {
  shopMoney {
    amount
  }
}

fragment PaymentTransactionDetails on OrderTransaction {
  accountNumber
  gateway
  paymentIcon {
    altText
  }
  status
  paymentIcon {
    altText
  }
}

