# query cost cannot exceed 1000 per x min
# query restores at 50 per second
# 
# with query below, first 50 costs - 1852
# with query below, first 40 costs - 1452
# with query below, first 30 costs - 1112
# with query below, first 29 costs - 1075
# with query below, first 28 costs - 1038
# with query below, first 27 costs - 1001
# with query below, first 26 costs - 964
# actual cost was 199



query GetOrders($user_query: String!){
  orders(first: 1, query: $user_query) {
    nodes {
      name
      updatedAt
      note
      tags
      displayFinancialStatus
      displayFulfillmentStatus
      channelInformation{channelDefinition{subChannelName handle}}
      lineItems(first: 10) {
        ...ProductSold
      }
      originalTotalPriceSet {
        ...PriceAmount
      }
      subtotalLineItemsQuantity
      customer {
        displayName
      }
      transactions(first: 10) {
        ...PaymentTransactionDetails
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      endCursor
    }
  }
}

fragment ProductSold on LineItemConnection {
  nodes {
    name
    quantity
    originalTotalSet {
      ...PriceAmount
    }
    originalUnitPriceSet {
      ...PriceAmount
    }
  }
}

fragment PriceAmount on MoneyBag {
  shopMoney {
    amount
  }
}

fragment PaymentTransactionDetails on OrderTransaction {
  accountNumber
  gateway
  paymentIcon {
    altText
  }
  status
}



